repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: check-vcs-permalinks
  - id: check-symlinks

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []
