[workspace]
allow_dirty = false
dependencies_update = true
git_release_enable = true
pr_labels = ["release"]
publish_allow_dirty = false
semver_check = true

[[package]]
name = "partial-context"
changelog_update = true
git_release_enable = true
publish = true
